# Generated by Django 3.2.25 on 2025-03-16 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_codetext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='codeText',
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('php', 'PHP'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL')], default='python', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('code', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='blog.post')),
            ],
        ),
    ]
